/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "zad1_f_1.v:1.1-3.10" *)
module gate(A, B, C, D, F);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "zad1_f_1.v:1.21-1.22" *)
  input A;
  wire A;
  (* src = "zad1_f_1.v:1.24-1.25" *)
  input B;
  wire B;
  (* src = "zad1_f_1.v:1.27-1.28" *)
  input C;
  wire C;
  (* src = "zad1_f_1.v:1.30-1.31" *)
  input D;
  wire D;
  (* src = "zad1_f_1.v:1.40-1.41" *)
  output F;
  wire F;
  NOT _4_ (
    .A(B),
    .Y(_0_)
  );
  NOT _5_ (
    .A(A),
    .Y(_1_)
  );
  NOR _6_ (
    .A(_1_),
    .B(C),
    .Y(_2_)
  );
  NOR _7_ (
    .A(D),
    .B(_2_),
    .Y(_3_)
  );
  NOR _8_ (
    .A(_0_),
    .B(_3_),
    .Y(F)
  );
endmodule
