/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* dynports =  1  *)
(* src = "shift_reg.v:1.1-18.10" *)
module shift_reg(d, clk, en, rstn, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "shift_reg.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "shift_reg.v:3.11-3.12" *)
  input d;
  wire d;
  (* src = "shift_reg.v:5.11-5.13" *)
  input en;
  wire en;
  (* src = "shift_reg.v:7.26-7.29" *)
  output [4:0] out;
  wire [4:0] out;
  (* src = "shift_reg.v:6.11-6.15" *)
  input rstn;
  wire rstn;
  MUX2X1 _15_ (
    .A(out[0]),
    .B(out[1]),
    .Q(_05_),
    .S(en)
  );
  AND2X1 _16_ (
    .A(rstn),
    .B(_05_),
    .Q(_04_)
  );
  MUX2X1 _17_ (
    .A(out[1]),
    .B(out[2]),
    .Q(_06_),
    .S(en)
  );
  AND2X1 _18_ (
    .A(rstn),
    .B(_06_),
    .Q(_00_)
  );
  MUX2X1 _19_ (
    .A(out[2]),
    .B(out[3]),
    .Q(_07_),
    .S(en)
  );
  AND2X1 _20_ (
    .A(rstn),
    .B(_07_),
    .Q(_01_)
  );
  MUX2X1 _21_ (
    .A(out[3]),
    .B(out[4]),
    .Q(_08_),
    .S(en)
  );
  AND2X1 _22_ (
    .A(rstn),
    .B(_08_),
    .Q(_02_)
  );
  MUX2X1 _23_ (
    .A(out[4]),
    .B(d),
    .Q(_09_),
    .S(en)
  );
  AND2X1 _24_ (
    .A(rstn),
    .B(_09_),
    .Q(_03_)
  );
  (* src = "shift_reg.v:9.5-17.12" *)
  DFX4 _25_ (
    .CP(clk),
    .D(_04_),
    .Q(out[0]),
    .QN(_14_)
  );
  (* src = "shift_reg.v:9.5-17.12" *)
  DFX4 _26_ (
    .CP(clk),
    .D(_00_),
    .Q(out[1]),
    .QN(_13_)
  );
  (* src = "shift_reg.v:9.5-17.12" *)
  DFX4 _27_ (
    .CP(clk),
    .D(_01_),
    .Q(out[2]),
    .QN(_12_)
  );
  (* src = "shift_reg.v:9.5-17.12" *)
  DFX4 _28_ (
    .CP(clk),
    .D(_02_),
    .Q(out[3]),
    .QN(_11_)
  );
  (* src = "shift_reg.v:9.5-17.12" *)
  DFX4 _29_ (
    .CP(clk),
    .D(_03_),
    .Q(out[4]),
    .QN(_10_)
  );
endmodule
