/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "vector.v:1.1-6.10" *)
module zad1_f_1(A, B, C, D, F);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "vector.v:2.11-2.12" *)
  input A;
  wire A;
  (* src = "vector.v:2.14-2.15" *)
  input B;
  wire B;
  (* src = "vector.v:2.17-2.18" *)
  input C;
  wire C;
  (* src = "vector.v:2.20-2.21" *)
  input D;
  wire D;
  (* src = "vector.v:3.12-3.13" *)
  output F;
  wire F;
  NOT _3_ (
    .A(C),
    .Y(_0_)
  );
  AND _4_ (
    .A(A),
    .B(_0_),
    .Y(_1_)
  );
  OR _5_ (
    .A(D),
    .B(_1_),
    .Y(_2_)
  );
  AND _6_ (
    .A(B),
    .B(_2_),
    .Y(F)
  );
endmodule

(* src = "vector.v:8.1-12.10" *)
module zad1_f_2(in, F);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "vector.v:9.10-9.11" *)
  wire A;
  (* src = "vector.v:9.13-9.14" *)
  wire B;
  (* src = "vector.v:9.16-9.17" *)
  wire C;
  (* src = "vector.v:9.19-9.20" *)
  wire D;
  (* src = "vector.v:8.40-8.41" *)
  output F;
  wire F;
  (* src = "vector.v:8.29-8.31" *)
  input [3:0] in;
  wire [3:0] in;
  OR _05_ (
    .A(in[2]),
    .B(in[3]),
    .Y(_01_)
  );
  OR _06_ (
    .A(in[1]),
    .B(_01_),
    .Y(_02_)
  );
  AND _07_ (
    .A(in[2]),
    .B(in[3]),
    .Y(_03_)
  );
  NOT _08_ (
    .A(_03_),
    .Y(_04_)
  );
  AND _09_ (
    .A(in[0]),
    .B(_04_),
    .Y(_00_)
  );
  AND _10_ (
    .A(_02_),
    .B(_00_),
    .Y(F)
  );
  assign A = in[3];
  assign B = in[2];
  assign C = in[1];
  assign D = in[0];
endmodule

(* src = "vector.v:14.1-21.10" *)
module zad1_f_3(in, F);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "vector.v:14.44-14.45" *)
  output F;
  wire F;
  (* src = "vector.v:14.29-14.31" *)
  input [3:0] in;
  wire [3:0] in;
  NOT _3_ (
    .A(in[1]),
    .Y(_0_)
  );
  AND _4_ (
    .A(_0_),
    .B(in[3]),
    .Y(_1_)
  );
  OR _5_ (
    .A(in[0]),
    .B(_1_),
    .Y(_2_)
  );
  AND _6_ (
    .A(in[2]),
    .B(_2_),
    .Y(F)
  );
endmodule
