/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "vector.v:1.1-8.10" *)
module zad1_f_3(in, F);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "vector.v:1.44-1.45" *)
  output F;
  wire F;
  (* src = "vector.v:1.29-1.31" *)
  input [3:0] in;
  wire [3:0] in;
  NOT _3_ (
    .A(in[1]),
    .Y(_0_)
  );
  AND _4_ (
    .A(_0_),
    .B(in[3]),
    .Y(_1_)
  );
  OR _5_ (
    .A(in[0]),
    .B(_1_),
    .Y(_2_)
  );
  AND _6_ (
    .A(in[2]),
    .B(_2_),
    .Y(F)
  );
endmodule
