/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "counter.v:1.1-16.10" *)
module register24(clk, rst_n, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "counter.v:1.26-1.29" *)
  input clk;
  wire clk;
  (* src = "counter.v:1.60-1.63" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "counter.v:1.37-1.42" *)
  input rst_n;
  wire rst_n;
  (* src = "counter.v:3.6-3.7" *)
  wire x;
  XNOR2X1 _4_ (
    .A(out[2]),
    .B(out[3]),
    .Q(x)
  );
  (* src = "counter.v:6.1-13.8" *)
  DFCX4 _5_ (
    .CP(clk),
    .D(x),
    .Q(out[0]),
    .QN(_1_),
    .RN(rst_n)
  );
  (* src = "counter.v:6.1-13.8" *)
  DFCX4 _6_ (
    .CP(clk),
    .D(out[0]),
    .Q(out[1]),
    .QN(_2_),
    .RN(rst_n)
  );
  (* src = "counter.v:6.1-13.8" *)
  DFCX4 _7_ (
    .CP(clk),
    .D(out[1]),
    .Q(out[2]),
    .QN(_3_),
    .RN(rst_n)
  );
  (* src = "counter.v:6.1-13.8" *)
  DFCX4 _8_ (
    .CP(clk),
    .D(out[2]),
    .Q(out[3]),
    .QN(_0_),
    .RN(rst_n)
  );
endmodule
