/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "counter.v:1.1-17.10" *)
module counter(clk, rst_n, cnt);
  (* src = "counter.v:1.23-1.26" *)
  input clk;
  wire clk;
  (* src = "counter.v:1.54-1.57" *)
  output [5:0] cnt;
  wire [5:0] cnt;
  (* src = "counter.v:3.11-3.17" *)
  wire [5:0] r_LFSR;
  (* src = "counter.v:4.5-4.11" *)
  wire r_XNOR;
  (* src = "counter.v:1.34-1.39" *)
  input rst_n;
  wire rst_n;
  assign cnt = 6'h00;
  assign r_LFSR = 6'b00000x;
  assign r_XNOR = 1'h1;
endmodule
