/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "register25.v:1.1-22.10" *)
module register25(clk, rstn, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* force_downto = 32'd1 *)
  (* src = "register25.v:0.0-0.0|register25.v:11.9-16.16|/usr/local/share/yosys/techmap.v:575.21-575.22" *)
  wire [5:0] _20_;
  (* src = "register25.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "register25.v:5.21-5.24" *)
  output [5:0] out;
  wire [5:0] out;
  (* src = "register25.v:4.11-4.15" *)
  input rstn;
  wire rstn;
  CLKINVX1 _21_ (
    .A(out[2]),
    .Q(_00_)
  );
  CLKINVX1 _22_ (
    .A(out[4]),
    .Q(_01_)
  );
  OR2X1 _23_ (
    .A(out[0]),
    .B(out[1]),
    .Q(_02_)
  );
  NAND2X1 _24_ (
    .A(out[2]),
    .B(_01_),
    .Q(_03_)
  );
  NOR4X1 _25_ (
    .A(_00_),
    .B(out[5]),
    .C(out[4]),
    .D(_02_),
    .Q(_04_)
  );
  NAND2X1 _26_ (
    .A(out[4]),
    .B(out[0]),
    .Q(_05_)
  );
  OR3X1 _27_ (
    .A(out[3]),
    .B(out[2]),
    .C(out[5]),
    .Q(_06_)
  );
  NOR3X1 _28_ (
    .A(out[1]),
    .B(_05_),
    .C(_06_),
    .Q(_07_)
  );
  NOR3X1 _29_ (
    .A(out[0]),
    .B(_04_),
    .C(_07_),
    .Q(_20_[0])
  );
  NAND2X1 _30_ (
    .A(out[0]),
    .B(out[1]),
    .Q(_08_)
  );
  NAND2X1 _31_ (
    .A(_02_),
    .B(_08_),
    .Q(_09_)
  );
  OAI32X1 _32_ (
    .A1(out[5]),
    .A2(_02_),
    .A3(_03_),
    .B1(_07_),
    .B2(_09_),
    .Q(_20_[1])
  );
  NAND3X1 _33_ (
    .A(out[2]),
    .B(out[0]),
    .C(out[1]),
    .Q(_10_)
  );
  XNOR2X1 _34_ (
    .A(out[2]),
    .B(_08_),
    .Q(_20_[2])
  );
  NAND4X1 _35_ (
    .A(out[3]),
    .B(out[2]),
    .C(out[0]),
    .D(out[1]),
    .Q(_11_)
  );
  XNOR2X1 _36_ (
    .A(out[3]),
    .B(_10_),
    .Q(_20_[3])
  );
  AND2X1 _37_ (
    .A(_01_),
    .B(_11_),
    .Q(_12_)
  );
  NOR2X1 _38_ (
    .A(_01_),
    .B(_11_),
    .Q(_13_)
  );
  NOR4X1 _39_ (
    .A(_04_),
    .B(_07_),
    .C(_12_),
    .D(_13_),
    .Q(_20_[4])
  );
  XOR2X1 _40_ (
    .A(out[5]),
    .B(_13_),
    .Q(_20_[5])
  );
  (* src = "register25.v:7.1-20.4" *)
  DFCX4 _41_ (
    .CP(clk),
    .D(_20_[0]),
    .Q(out[0]),
    .QN(_15_),
    .RN(rstn)
  );
  (* src = "register25.v:7.1-20.4" *)
  DFCX4 _42_ (
    .CP(clk),
    .D(_20_[1]),
    .Q(out[1]),
    .QN(_16_),
    .RN(rstn)
  );
  (* src = "register25.v:7.1-20.4" *)
  DFCX4 _43_ (
    .CP(clk),
    .D(_20_[2]),
    .Q(out[2]),
    .QN(_17_),
    .RN(rstn)
  );
  (* src = "register25.v:7.1-20.4" *)
  DFCX4 _44_ (
    .CP(clk),
    .D(_20_[3]),
    .Q(out[3]),
    .QN(_18_),
    .RN(rstn)
  );
  (* src = "register25.v:7.1-20.4" *)
  DFCX4 _45_ (
    .CP(clk),
    .D(_20_[4]),
    .Q(out[4]),
    .QN(_19_),
    .RN(rstn)
  );
  (* src = "register25.v:7.1-20.4" *)
  DFCX4 _46_ (
    .CP(clk),
    .D(_20_[5]),
    .Q(out[5]),
    .QN(_14_),
    .RN(rstn)
  );
endmodule
