/* Generated by Yosys 0.16+41 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "register26.v:1.1-18.10" *)
module register26(clk, rst_n, D);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* force_downto = 32'd1 *)
  (* src = "register26.v:8.29-8.38|/usr/local/share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _11_;
  (* force_downto = 32'd1 *)
  (* src = "register26.v:8.29-8.38|/usr/local/share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "register26.v:1.53-1.54" *)
  output [3:0] D;
  wire [3:0] D;
  (* src = "register26.v:1.25-1.28" *)
  input clk;
  wire clk;
  (* init = 4'bx0xx *)
  (* src = "register26.v:2.19-2.24" *)
  wire [3:0] delta;
  (* src = "register26.v:1.30-1.35" *)
  input rst_n;
  wire rst_n;
  CLKINVX1 _17_ (
    .A(D[2]),
    .Q(_01_)
  );
  NAND2X1 _18_ (
    .A(D[1]),
    .B(delta[2]),
    .Q(_02_)
  );
  XOR2X1 _19_ (
    .A(D[1]),
    .B(delta[2]),
    .Q(_03_)
  );
  XNOR2X1 _20_ (
    .A(_11_[0]),
    .B(_03_),
    .Q(_12_[1])
  );
  OAI21X1 _21_ (
    .A1(D[1]),
    .A2(delta[2]),
    .B1(D[0]),
    .Q(_04_)
  );
  AND2X1 _22_ (
    .A(_02_),
    .B(_04_),
    .Q(_05_)
  );
  XOR2X1 _23_ (
    .A(D[2]),
    .B(delta[2]),
    .Q(_06_)
  );
  XNOR2X1 _24_ (
    .A(_05_),
    .B(_06_),
    .Q(_12_[2])
  );
  NOR3X1 _25_ (
    .A(_01_),
    .B(delta[2]),
    .C(_04_),
    .Q(_07_)
  );
  AOI31X1 _26_ (
    .A1(_01_),
    .A2(delta[2]),
    .A3(_05_),
    .B1(_07_),
    .Q(_08_)
  );
  XNOR2X1 _27_ (
    .A(D[3]),
    .B(_08_),
    .Q(_12_[3])
  );
  OAI21X1 _28_ (
    .A1(D[2]),
    .A2(D[3]),
    .B1(delta[2]),
    .Q(_09_)
  );
  AOI31X1 _29_ (
    .A1(D[1]),
    .A2(D[2]),
    .A3(D[3]),
    .B1(delta[2]),
    .Q(_10_)
  );
  AOI31X1 _30_ (
    .A1(D[0]),
    .A2(_02_),
    .A3(_09_),
    .B1(_10_),
    .Q(_00_)
  );
  (* src = "register26.v:12.9-17.12" *)
  DFX4 _31_ (
    .CP(clk),
    .D(_00_),
    .Q(delta[2]),
    .QN(_14_)
  );
  (* src = "register26.v:4.9-11.12" *)
  DFCX4 _32_ (
    .CP(clk),
    .D(_11_[0]),
    .Q(D[0]),
    .QN(_11_[0]),
    .RN(rst_n)
  );
  (* src = "register26.v:4.9-11.12" *)
  DFCX4 _33_ (
    .CP(clk),
    .D(_12_[1]),
    .Q(D[1]),
    .QN(_15_),
    .RN(rst_n)
  );
  (* src = "register26.v:4.9-11.12" *)
  DFCX4 _34_ (
    .CP(clk),
    .D(_12_[2]),
    .Q(D[2]),
    .QN(_16_),
    .RN(rst_n)
  );
  (* src = "register26.v:4.9-11.12" *)
  DFCX4 _35_ (
    .CP(clk),
    .D(_12_[3]),
    .Q(D[3]),
    .QN(_13_),
    .RN(rst_n)
  );
  assign _12_[0] = _11_[0];
  assign { delta[3], delta[1:0] } = { delta[2], delta[2], 1'h1 };
endmodule
